<?php

namespace Framework\Core\Console\Commands;

use Framework\Core\Console\Command;
use Framework\Core\Routing\Router;

/**
 * `php console route:cache`
 *
 * Loads every route from `routes/**\/*.php` fresh, compiles patterns, and
 * dumps the result to `bootstrap/cache/routes.php`. Subsequent requests
 * bypass the recursive file walk in Kernel::handle() entirely and load
 * routes directly from the cached PHP array.
 *
 * Refuses to cache routes that use closures or object middleware — those
 * can't survive `var_export`. Convert closure handlers to
 * `[Controller::class, 'method']` shape before caching.
 */
class RouteCacheCommand extends Command
{
    public function execute(): void
    {
        $rootPath  = dirname(dirname(dirname(__DIR__)));
        $cacheDir  = $rootPath . '/bootstrap/cache';
        $cacheFile = $cacheDir . '/routes.php';
        $routesDir = $rootPath . '/routes';

        if (!is_dir($routesDir)) {
            $this->error("No routes/ directory at {$routesDir}.");
            return;
        }
        if (!is_dir($cacheDir)) {
            @mkdir($cacheDir, 0755, true);
        }

        // Start from a clean slate so a stale in-process registration
        // doesn't leak into the cache.
        Router::clearRoutes();

        // Load routes fresh from disk. No request/response is set — the
        // handlers won't run, we're just capturing the registration.
        Router::loadRoutesFrom($routesDir);

        try {
            $data = Router::exportRoutesForCache();
        } catch (\RuntimeException $e) {
            $this->error($e->getMessage());
            $this->info("Route caching aborted.");
            return;
        }

        // var_export gives a static PHP literal that can be require()'d.
        // A short helper header explains what generated the file so nobody
        // hand-edits it.
        $php  = "<?php\n\n";
        $php .= "// Auto-generated by `php console route:cache`.\n";
        $php .= "// Regenerate after any change to routes/. Delete via `php console route:clear`.\n";
        $php .= "// Generated at: " . $data['generated_at'] . "\n\n";
        $php .= "return " . var_export($data, true) . ";\n";

        if (file_put_contents($cacheFile, $php) === false) {
            $this->error("Failed to write {$cacheFile}.");
            return;
        }

        $count = count($data['routes']);
        $this->success("Cached {$count} route(s) to bootstrap/cache/routes.php.");
    }
}
